Repository Deepomatic/dmake, pull requests merged in 2020-05, with the labels that each got.

#447 Simplify base image building: raw root image
  dmake/deepobuild.py
  dmake/templates/docker-base-raw-root-image/make_base.sh
  test/web/dmake.yml
  test/worker/deploy/dependencies.sh
  test/worker/dmake.yml
  tutorial/web/deploy/dependencies.sh
  tutorial/web/dmake.yml
  tutorial/worker/deploy/dependencies.sh
  tutorial/worker/dmake.yml
Labels: READY, enhancement

#448 Test non-regression trailing slash in html_report dir copy
  dmake/core.py
  test/web/dmake.yml
Labels: READY, bug

#449 Test kubernetes deployment manifest templates in PRs
  Jenkinsfile
  dmake/templates/jenkins/Jenkinsfile
Labels: READY, area/jenkins, area/test, enhancement

#451 install.sh: support .{bash,zsh}rc with no trailing newline
  install.sh
Labels: bug
